// Mocks generated by Mockito 5.4.4 from annotations
// in quaketrack/test/sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:geolocator/geolocator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:quaketrack/models/earthquake.dart' as _i5;
import 'package:quaketrack/services/api_service.dart' as _i3;
import 'package:quaketrack/services/geocoding_service.dart' as _i7;
import 'package:quaketrack/services/location_service.dart' as _i8;
import 'package:quaketrack/services/websocket_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  @override
  _i4.Future<List<_i5.Earthquake>> fetchEarthquakes(
    String? provider,
    double? minMagnitude,
    double? radius,
    double? latitude,
    double? longitude, {
    String? timeWindow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEarthquakes,
          [
            provider,
            minMagnitude,
            radius,
            latitude,
            longitude,
          ],
          {#timeWindow: timeWindow},
        ),
        returnValue: _i4.Future<List<_i5.Earthquake>>.value(<_i5.Earthquake>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Earthquake>>.value(<_i5.Earthquake>[]),
      ) as _i4.Future<List<_i5.Earthquake>>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i6.WebSocketService {
  @override
  _i4.Stream<_i5.Earthquake> get earthquakeStream => (super.noSuchMethod(
        Invocation.getter(#earthquakeStream),
        returnValue: _i4.Stream<_i5.Earthquake>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Earthquake>.empty(),
      ) as _i4.Stream<_i5.Earthquake>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GeocodingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeocodingService extends _i1.Mock implements _i7.GeocodingService {
  @override
  _i4.Future<String?> reverseGeocode(
    double? eqLat,
    double? eqLon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reverseGeocode,
          [
            eqLat,
            eqLon,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> getCountryCode(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountryCode,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  @override
  _i4.Future<_i2.Position> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i4.Future<_i2.Position>.value(_FakePosition_0(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Position>.value(_FakePosition_0(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Position>);

  @override
  _i4.Future<_i2.LocationPermission> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i4.Future<_i2.LocationPermission>.value(
            _i2.LocationPermission.denied),
        returnValueForMissingStub: _i4.Future<_i2.LocationPermission>.value(
            _i2.LocationPermission.denied),
      ) as _i4.Future<_i2.LocationPermission>);

  @override
  _i4.Future<_i2.LocationPermission> checkPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [],
        ),
        returnValue: _i4.Future<_i2.LocationPermission>.value(
            _i2.LocationPermission.denied),
        returnValueForMissingStub: _i4.Future<_i2.LocationPermission>.value(
            _i2.LocationPermission.denied),
      ) as _i4.Future<_i2.LocationPermission>);

  @override
  _i4.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
