include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add your preferred linting rules here.
    # For a full list of available rules, see:
    # https://dart.dev/tools/linter-rules
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
